### ISSUE TITLE
sabnzd stopped working after reboot

### ISSUE THREAD

**Issue by ramonskie** [lsellens/script.service.audo#20]
when i try to load i manully with 

```
python /storage/.kodi/addons/script.module.audo-programs/resources/SABnzbd/SABnzbd.py --pid_file=/var/run/sabnzbd.pid --data_dir /storage/.kodi/userdata/addon_data/script.service.audo --config=/storage/.kodi/userdata/addon_data/script.service.audo/sabnzbd.ini --daemon
```

i get The Python module Cheetah is required

**Comment by Shinzah** [comment]
Same for me :(

**Comment by fboyer** [comment]
Same here, for some reason sabnzbd stopped running a few days ago and I cannot get it to start again.

**Comment by rtandonmsft** [comment]
+1 on this. I recently updated from openelec to libreelec and while trying to get transmission to work again with the repo, audo got updated and sabnzbd stopped working.

Will try to figure a workaround until its fixed.

**Comment by ramonskie** [comment]
if anyone has found a workaround please post it here :)

**Comment by lsellens** [comment]
Manually launching any part of the suite will give you dependency issues due to them not being in path. Its only available in the kodi python namespace hence the cheetah error. Not certain what’s wrong with sab at the current moment. I Don't use sab, and honestly do not test it during updates. I'm leaving for Las Vegas tomorrow I'll push an update with a earlier version that's known to work for tonight and will figure out why the new version isn't launching correctly when I get back in town.

**Comment by rtandonmsft** [comment]
Thanks for the prompt response @Isellens.

@ramonskie  - This thread has a workaround mentioned (same lines as what Isellens plans to do)

http://openelec.tv/forum/80-sabnzbd-suite/82371-issue-starting-sabnzbd-on-audo-since-yesterday?limitstart=0

Between the previous and newer version of audo, the Sab version did get updated from 1.0.3 to 1.1.0RC2 and the repo change. Haven't checked the source of Sab either on what changes were made.

Commit:
https://github.com/lsellens/script.module.audo-programs/commit/0bd41ca8f871e2445cbf12f2888b9bfecf47439d

**Comment by usenetuser** [comment]
Thanks for the prompt response @lsellens
SYSTEM)
@ramonskie - This thread has a workaround mentioned (same lines as what @lsellens plans to do)

http://openelec.tv/forum/80-sabnzbd-suite/82371-issue-starting-sabnzbd-on-audo-since-yesterday?limitstart=0

Between the previous and newer version of audo, the Sab version did get updated from 1.0.3 to 1.1.0RC2 and the repo change. Haven't checked the source of Sab either on what changes were made.

Commit:
lsellens/script.module.audo-programs@0bd41ca

Here is the link to log:
KODI Log - http://pastebin.com/4WsQgQSb

Looks like a sabnzbd issue than audo.

This log does not indicate sabnzbd daemon being started, while other audo services are:
SYSTEM Log - http://pastebin.com/e0MGbLDx

**Comment by ramonskie** [comment]
removed an reinstalled.
but all services are not starting "sick & couch are starting manuall"

switched to nzbget. nothing and also no logs in /.kodi/userdata/addon_data/script.service.audo/logs

i get this with debug logging though

```
15:03:33 T:1667638336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named configobj
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.audo/service.py", line 3, in <module>
                                                import resources.audo as audo
                                              File "/storage/.kodi/addons/script.service.audo/resources/audo.py", line 2, in <module>
                                                from configobj import ConfigObj
                                            ImportError: No module named configobj
                                            -->End of Python script error report<--
```

**Comment by lsellens** [comment]
md5sum
b285ef644bed6c1330be386505b1abd4  script.module.audo-dependencies-0.1.1.zip
if this doesn't match then redownload

**Comment by lsellens** [comment]
this should be resolved with newer versions. If not then please reopen.
